[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = 5000 }

# Database migrations will run automatically on deploy
[[deploy.healthcheck]]
path = "/health"
intervalSeconds = 30
timeoutSeconds = 10