services:
  - type: web
    name: career-mirror
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: career-mirror-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
        
databases:
  - name: career-mirror-db
    databaseName: career_mirror
    plan: starter