name: Deploy to Railway

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Upload build artifact (server+client)
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: |
            dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ secrets.RAILWAY_TOKEN != '' }}
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_ENVIRONMENT: ${{ secrets.RAILWAY_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Link Railway project (optional)
        if: ${{ env.RAILWAY_PROJECT_ID != '' }}
        run: |
          railway link --project $RAILWAY_PROJECT_ID
          if [ -n "$RAILWAY_ENVIRONMENT" ]; then
            railway environment use "$RAILWAY_ENVIRONMENT"
          fi

      - name: Deploy to Railway (Nixpacks)
        run: |
          railway up --ci
